# Generated by Django 2.2.5 on 2019-12-29 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='이름', max_length=140)),
                ('description', models.TextField()),
                ('city', models.CharField(help_text='도시', max_length=80)),
                ('price', models.IntegerField(help_text='가격')),
                ('address', models.CharField(help_text='주소', max_length=140)),
                ('guests', models.IntegerField(help_text='인원수')),
                ('beds', models.IntegerField(help_text='침대')),
                ('bedrooms', models.IntegerField(help_text='침실')),
                ('baths', models.IntegerField(help_text='화장실')),
                ('check_in', models.TimeField(help_text='체크인')),
                ('check_out', models.TimeField(help_text='체크아웃')),
                ('instant_book', models.BooleanField(default=False, help_text='바로예약')),
                ('host', models.ForeignKey(help_text='호스트', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
