# Generated by Django 2.2.5 on 2019-12-30 12:14

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
