# Generated by Django 2.2.5 on 2019-12-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('confirmed', '확인'), ('canceled', '취소')], default='pending', max_length=12),
        ),
    ]
