# Generated by Django 2.2.5 on 2019-12-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='accuracy',
            field=models.IntegerField(help_text='정확성'),
        ),
        migrations.AlterField(
            model_name='review',
            name='check_in',
            field=models.IntegerField(help_text='체크인'),
        ),
        migrations.AlterField(
            model_name='review',
            name='cleanliness',
            field=models.IntegerField(help_text='청결'),
        ),
        migrations.AlterField(
            model_name='review',
            name='communication',
            field=models.IntegerField(help_text='통신'),
        ),
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.IntegerField(help_text='위치'),
        ),
    ]
